version: "3"

services:
  mongo-express:
   image: mongo-express
   depends_on:
     - 'mongo'
   ports:
     - 8035:8081
   environment:
     ME_CONFIG_BASICAUTH_USERNAME: hublab
     ME_CONFIG_BASICAUTH_PASSWORD: Passw0rd
     ME_CONFIG_MONGODB_PORT: 27030
     ME_CONFIG_MONGODB_ADMINUSERNAME: root
     ME_CONFIG_MONGODB_ADMINPASSWORD: Passw0rd

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: hublab_chat
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Passw0rd
    ports:
      - "27030:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro